name: Jenkins Install Tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  jenkins-lts:
    runs-on: ubuntu-latest
    name: test on jenkins lts
    steps:
      - uses: actions/checkout@v3
      - name: test jenkins-lts
        uses: ./test/jenkins-lts/
        env:
          GITHUB_SHA_BRANCH: develop

  # last good version: to update it, run "update-version.yml" workflow
  jenkins-last:
    runs-on: ubuntu-latest
    name: test on jenkins last good version
    steps:
      - uses: actions/checkout@v3
      - name: test jenkins-last
        uses: ./test/jenkins-last/
        env:
          GITHUB_SHA_BRANCH: develop
        
